import jsPDF from 'jspdf'
import { Download } from 'lucide-react'
import { format } from 'date-fns'

interface Props {
  session: any
}

export default function PDFDownloadButton({ session }: Props) {
  const handleDownload = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - 2 * margin
    let y = 20

    // Helper to add text with word wrap
    const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
      doc.setFontSize(fontSize)
      if (isBold) doc.setFont('helvetica', 'bold')
      else doc.setFont('helvetica', 'normal')

      const lines = doc.splitTextToSize(text, maxWidth)
      lines.forEach((line: string) => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(line, margin, y)
        y += fontSize * 0.5
      })
      y += 2
    }

    const addSection = (title: string, items: string[]) => {
      if (items.length === 0) return
      y += 3
      addText(title, 12, true)
      y += 2
      items.forEach(item => {
        addText(`• ${item}`, 10, false)
      })
    }

    const parseArray = (field: any) => {
      if (!field) return []
      if (Array.isArray(field)) return field
      try { return JSON.parse(field) } catch { return [] }
    }

    // Title
    addText(session.summary_title || 'Session Summary', 16, true)
    y += 2

    // Metadata
    addText(`Date: ${format(new Date(session.started_at * 1000), 'PPpp')}`, 9, false)
    addText(`Status: ${session.summary_status || session.status}`, 9, false)

    if (session.summary_mood) {
      addText(`Mood: ${session.summary_mood}`, 9, false)
    }
    if (session.summary_complexity) {
      addText(`Complexity: ${session.summary_complexity}`, 9, false)
    }
    if (session.summary_key_insight) {
      y += 2
      addText(`💡 ${session.summary_key_insight}`, 10, true)
    }

    // Sections
    addSection('What We Did', parseArray(session.summary_what_we_did))
    addSection('Decisions Made', parseArray(session.summary_decisions))
    addSection('Blockers', parseArray(session.summary_blockers))
    addSection('Resolved', parseArray(session.summary_resolved))
    addSection('Files Changed', parseArray(session.summary_files_changed))
    addSection('Next Steps', parseArray(session.summary_next_steps))
    addSection('Gotchas / Remember', parseArray(session.summary_gotchas))
    addSection('Tech Notes', parseArray(session.summary_tech_notes))

    // Footer
    y += 5
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(`Generated by ClaudeContext on ${format(new Date(), 'PPpp')}`, margin, y)

    // Download
    const filename = `session-${session.id.slice(0, 8)}-${format(new Date(session.started_at * 1000), 'yyyy-MM-dd')}.pdf`
    doc.save(filename)
  }

  return (
    <button
      onClick={handleDownload}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        padding: '6px 12px',
        background: 'var(--red)15',
        color: 'var(--red)',
        border: '1px solid var(--red)30',
        borderRadius: 8,
        fontSize: 12,
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'all 0.15s',
      }}
      onMouseEnter={e => (e.currentTarget.style.background = 'var(--red)25')}
      onMouseLeave={e => (e.currentTarget.style.background = 'var(--red)15')}
    >
      <Download size={14} />
      PDF
    </button>
  )
}
